backbone: "CLIP-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 20

seed: 0
deterministic: True
gpu: 0
num_workers: 8
prec: "amp"
#prec: "fp16"
tte: False
expand: 24

mu_u: 1 # ratio of batch size of unlabeled data to positive data
num_epochs: 50
num_iterations_per_epoch: 500
batch_size: 32
lr: 0.1
weight_decay: 5e-4
momentum: 0.9
#init_head: "text_feat"

loss_type: "nnPU"
classifier: "LinearClassifier"

bias_tuning: False
bn_tuning: False
ssf_attn: False
vpt_shallow: True

ls_weight: 0.1
threshold: 0.9
